services:
  fastapi:
    image: pnapat/fastapi-review:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:8000

  streamlit:
    image: pnapat/streamlit-review:dev
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports: 
      - 8501:8501
    environment:  # Environment variables inside the container
      API_URL: http://fastapi:8000   # other containers can reach it by this name (send request to here)