apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamlit-review
  name: streamlit-review
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit-review
  strategy: {}
  template:
    metadata:
      labels:
        app: streamlit-review
    spec:
      containers:
      - image: pnapat/streamlit-review:v3
        name: streamlit-review
        ports:
        - containerPort: 8501
        resources: {}
status: {}
